### ISSUE TITLE
Inventory: endpoints to subtract/add amount in stock

### ISSUE THREAD

**Issue by thezeroalpha** [BU-NU-CLOUD-F19/Cloud_Based_E-Commerce_Platform#14]
There should be two endpoints, to add and subtract amount in stock for a single product.
i.e., give it an object like:

```json
{
  "pid": 1,
  "amount": 3
}
```

And the handlers should update the amount in stock for an item accordingly. They should also take care of errors such as trying to subtract from an item that's not in stock.

**Comment by samarth18** [comment]
Can't we handle updating the stock by making a PUT request to the endpoint `inventory/{pid}`?

**Comment by thezeroalpha** [comment]
I'm currently working on the checkout service, which made me think of these endpoints.

It could be handled with a PUT request to the existing endpoint, but that requires:

1) Sending unrelated information about the product just to update the amount (price, pname, description, lang)
2) Knowing the current amount in the inventory (results in an extra GET request to the inventory)
3) Doing inventory-related checks outside of the inventory service (i.e. is there enough of this item in stock to subtract 3?)

Hence I figured it would be better to have these as part of the inventory API.

**Comment by thezeroalpha** [comment]
Implemented in d1cf46b.
